export const USERS_FETCH_START = 'USERS_FETCH_START';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_NO_MORE = 'USERS_FETCH_NO_MORE';
export const USERS_ADD_SUCCESS = 'USERS_ADD_SUCCESS';
export const USERS_ADD_ERROR = 'USERS_ADD_ERROR';
export const USERS_RM_SUCCESS = 'USERS_RM_SUCCESS';

export const PEMANAGER_FETCH_START = 'PEMANAGER_FETCH_START';
export const PEMANAGER_FETCH_SUCCESS = 'PEMANAGER_FETCH_SUCCESS';
export const PEMANAGER_FETCH_NO_MORE = 'PEMANAGER_FETCH_NO_MORE';
export const PEMANAGER_ADD_SUCCESS = 'PEMANAGER_ADD_SUCCESS';
export const PEMANAGER_ADD_ERROR = 'PEMANAGER_ADD_ERROR';
export const PEMANAGER_RM_SUCCESS = 'PEMANAGER_RM_SUCCESS';

export const REVIEWS_FETCH_START = 'REVIEWS_FETCH_START';
export const REVIEWS_FETCH_SUCCESS = 'REVIEWS_FETCH_SUCCESS';
export const REVIEWS_FETCH_NO_MORE = 'REVIEWS_FETCH_NO_MORE';
export const REVIEWS_ADD_SUCCESS = 'REVIEWS_ADD_SUCCESS';
export const REVIEWS_ADD_ERROR = 'REVIEWS_ADD_ERROR';
export const REVIEWS_RM_SUCCESS = 'REVIEWS_RM_SUCCESS';
