export const PEMANAGER_FETCH_START = 'PEMANAGER_FETCH_START';
export const PEMANAGER_FETCH_SUCCESS = 'PEMANAGER_FETCH_SUCCESS';
export const PEMANAGER_FETCH_NO_MORE = 'PEMANAGER_FETCH_NO_MORE';
export const PEMANAGER_ADD_SUCCESS = 'PEMANAGER_ADD_SUCCESS';
export const PEMANAGER_ADD_ERROR = 'PEMANAGER_ADD_ERROR';
