export const PEMANAGER_FETCH_START = 'PEMANAGER_FETCH_START';
export const PEMANAGER_FETCH_SUCCESS = 'PEMANAGER_FETCH_SUCCESS';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_FETCH_START = 'REVIEW_FETCH_START';
export const REVIEW_FETCH_SUCCESS = 'REVIEW_FETCH_SUCCESS';
export const REVIEW_FETCH_NO_MORE = 'REVIEW_FETCH_NO_MORE';
export const RAPORT_ADD_SUCCESS = 'RAPORT_ADD_SUCCESS';
export const THUMB_ADD_SUCCESS = 'THUMB_ADD_SUCCESS';
