export const USER_FETCH_START = 'USER_FETCH_START';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const REVIEW_FETCH_START = 'REVIEW_FETCH_START';
export const REVIEW_FETCH_SUCCESS = 'REVIEW_FETCH_SUCCESS';
export const REVIEW_FETCH_NO_MORE = 'REVIEW_FETCH_NO_MORE';
